# Generated by Django 3.2.16 on 2022-11-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user_id', models.CharField(max_length=100)),
                ('to_user_id', models.CharField(max_length=100)),
                ('datum', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.IntegerField(max_length=100)),
                ('lehrer_init', models.CharField(max_length=100)),
                ('user_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usertype')),
            ],
        ),
    ]
